language: python
python:
  - "3.6"
  - "3.6-dev"
  - "nightly"
install:
  - pip install pip-tools
  - pip-sync requirements/dev.txt
  - pip install coveralls
script: make coverage
after_success: coveralls
